FROM alpine:3


RUN apk update -f \
  && apk --no-cache add -f \
  curl ca-certificates \
  iproute2 net-tools iptables \
  wireguard-tools openresolv \
  v2ray \
  && rm -rf /var/cache/apk/*
  
  
RUN curl -fsSL git.io/wgcf.sh | bash && mkdir -p /wgcf

WORKDIR /wgcf

VOLUME /wgcf

COPY config.json /etc/v2ray/

COPY entry.sh /entry.sh
RUN chmod +x /entry.sh

ENTRYPOINT ["/entry.sh"]


